spring.application.name=professores-api

spring.datasource.url=jdbc:postgresql://localhost:2115/escola
spring.datasource.username=postgres
spring.datasource.password=esperantina098

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
